#!/bin/bash

exec &> /dev/null

while read -r arg; do
	# first try matching by filename or pathname
	case "${arg,,}" in
		wi\:*)
			target=$(echo "$arg"|cut -d' ' -f2-)
            DISPLAY=":0.0" /usr/bin/xdotool search --desktop 0 --limit 1 --name "$target" windowfocus
			;;
        da*)
            /usr/bin/firefox -new-tab http://192.168.1.222:3000/d/ceiwfytnasbnkf/important?orgId=1&from=now-24h&to=now&timezone=browser&refresh=30s
            ;;
        ii*)
            /usr/bin/firefox -new-tab https://notes.nikonov.tech/ideas_inbox
            ;;
        rr*)
            /usr/bin/firefox -new-tab https://notes.nikonov.tech
            ;;
        rs*)
            /usr/bin/firefox -new-tab https://reader.nikonov.tech/i/
            ;;
        ch*)
            /usr/bin/firefox -new-tab "https://chatgpt.com/?temporary-chat=true&model=o3-mini"
            ;;
        ed*)
            /usr/bin/firefox -new-tab "https://excalidraw.com/"
            ;;
        *.desktop)
            gtk-launch "$arg" &
            ;;
		*)
            xdg-open "https://www.google.com/search?q=$arg" &
            ;;
	esac
done
