#!/bin/bash

exec &> /dev/null

while read -r arg; do
	# first try matching by filename or pathname
	case "${arg,,}" in
		0x*)
			target=$(echo "$arg"|cut -d' ' -f1)
            xdotool windowfocus "$target" &
			;;
        ii*)
            /usr/bin/firefox -new-tab https://notes.nikonov.tech/ideas_inbox
            ;;
        rr*)
            /usr/bin/firefox -new-tab https://notes.nikonov.tech
            ;;
        rs*)
            /usr/bin/firefox -new-tab https://reader.nikonov.tech/i/
            ;;
        ch*)
            /usr/bin/firefox -new-tab "https://chatgpt.com/?temporary-chat=true&model=o3-mini"
            ;;
        *.desktop)
            gtk-launch "$arg" &
            ;;
		*)
            xdg-open "$arg" &
            ;;
	esac
done
